### ISSUE TITLE
support 60GHz interface

### ISSUE THREAD

**Issue by ZeroChaos-** [kkonradpl/mtscan#8]
I'm attempting to use wap60g and/or wap60gap as a sniffer.  It's a bit odd, but it seems to work when I do the following:

```
interface w60g set wlan60-1 mode=sniff
```

Unfortuntely, the mtscan gui won't accept `w60g` or `wlan60-1` as an interface name.

I'll try to take a stab at figuring this out in the code, but I wanted to make sure the feature request was logged.

**Comment by ZeroChaos-** [comment]
both scanner and sniffer don't work.  In the winbox gui I can use scanner as normal, but it's under the w60g tab not the wireless tab.
The gui doesn't offer sniffer support, but if I enable it via command line, things seem to happen.  It's streaming something to wireshark anyway, not really sure what yet :-)

**Comment by kkonradpl** [comment]
Currently there is only support for `interface wireless`, i.e. regular 802.11 a/b/g/n/ac interfaces (see mt-ssh.c).

I'm not familiar of the 802.11ad or any Mikrotik-specific 60 GHz protocol (haven't used any wap60g hardware). Look for some beacon frames in the sniffer capture, maybe it would be possible to write a beacon parser (see src/tzsp directory). This would be the recommended way. The scanner mode in MTscan should be generally considered as deprecated, as it parses the scanning output from SSH. This is quite tricky and there are some major disadvantages of that approach.

**Comment by ZeroChaos-** [comment]
Turns out, it doesn't seem to capture in the 60g band at this time, with the latest firmware.  I may reopen this if mikrotik adds support.  thanks!
